imenyk1=input("введи перший іменнник: ")
imenyk2 = input("введи другий іменник: ")
diesl = input("введи дієслово: ")
prysl = input("введи прислівник: ")
imenyk3 = input("введи третій іменник: ")
print(f"{imenyk1} йшов по стежці")
print(f"і зустрів{imenyk2} ")
print(f"він його{diesl}")
print(f"і пішов {prysl}.")
